baseURL: "https://kfarivar.github.io/"
languageCode: "en-us"
title: "Kia personal website"
theme: "profile"
publishDir: "docs"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: ""
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/dog.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Kiarash's website" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Kiarash"
    subtitle: "I am passionate about ML and DL."
    content: "I like exploring new applications of ML and DL and improving their shortcomings. I studied adversarial examples during my masters thesis."
    image: /profile.jpg
    roundImage: true # Make hero image circular | default false
    #button:
    #  enable: true
     # name: "Resume"
      #url: "#"
      #download: true
      #newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: http://github.com/kfarivar
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/kiarash-farivar-7048951b8/
      #customIcons:
        #- icon: /fav.png
          #url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am an ML engineer with a passion for research. I have a background in computer science and mathematics. I am currently working as an ML engineer at [CGG](https://www.cgg.com/) in the UK. 


    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Pytorch"
        - "Python"
        - "Spark"
        - "Pytorch Lightining"
        - "Machine vision"
        - "Adversarial examples"

  # Experience
  experience:
    enable: true
    #title: "Custom Name"
    items:
      - job: "ML engineer"
        company: "CGG"
        companyUrl: "https://www.cgg.com"
        date: "March 2023 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a ML engineer at CGG in the UK."
        
      - job: "Master's Thesis"
        company: "EPFL"
        #companyUrl: "https://example.com"
        date: "Feb 2021 - Jul 2022"
        info:
          enable: false
        featuredLink:
          enable: true
          name: "view project"
          url: "https://github.com/kfarivar/Masters_thesis"
        content: |
          The loss function is supposed to be a proxy for the model accuracy. But this proxy is not always perfect. I explored how the definition of the loss function and the specific method of learning used (self-supervised or supervised) affects the robustness of a model to adversarial examples. I further explored the adversarial problem in synthetic datasets and showed that under specific assumptions the standard deep learning pipeline can learn a robust model. Before this I worked on Disentangling Adversarial examples. I explored different factors that can contribute to the phenomena of adversarial examples. I examined robust training, the saliency maps of the robust model, methods for estimating the smoothness of the decision boundary (like CLEVER score), and estimating the concentration of the dataset. I created a library to automate the process of evaluating the above phenomena.

          - Created a library for evaluating advresarial robustness.
          - Benchmarked robustness of different self-supervised methods.
          - Created a toy dataset to show the possiblility of training a robust model using standard training. 
          
      - job: "Research And Development Intern"
        company: "Logitech"
        #companyUrl: "https://example.com"
        date: "Sep 2020 - Feb 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: 
          I investigated possible solutions to reconstruct 3D bodies using multiple RGB-depth Kinect cameras. I experimented with both optimizing parametric models (SMPL) and using non-parametric models. I investigated possible solutions such as IF-net and IP-net from the Max Planck Institute.
          
      - job: "Semester project"
        company: "EPFL"
        #companyUrl: "https://example.com"
        date: "Feb 2020 - Jun 2020"
        featuredLink:
          enable: true
          url: "https://github.com/kfarivar/3DPoint_Cloud_Segmentation_Semester_Project"
        info:
          enable: false
        content: 
           I used Pointnet++ to classify points and detect different instances of pipes in a 3D point cloud (i.e. instance segmentation) using Pytorch. The pointcloud was collected using a LIDAR scanner. 

        
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Data Science"
        school:
          name: "École Polytechnique Fédérale de Lausanne (EPFL), Switzerland"
          #url: "https://example.org"
        date: "2018 - 2022"
        GPA: "5.2 out of 6.0"
        content: |-
          I was mostly involved with ML and DL related courses.
      
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Shahid Beheshti University (SBU), Iran"
          #url: "https://example.org"
        date: "2013 - 2018"
        GPA: "18.9 out of 20.0"
        #content: |-
          
      

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    #socialNetworks:
      #github: https://github.com
      #linkedin: https://linkedin.com
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
